### ISSUE TITLE
file revision/date code/issue version

### ISSUE THREAD

**Issue by meee1** [ArduPilot/useralerts#5]
need a quick method to determine if something has changed, both at a manifest level, and an alert level.

ie if a Fixed date has been added, there should be some version number/last changed date so the alert can be displayed to the user.

this way form the GCS i can check for items that have changed since a last view/acknowledged time. currently i would need to hash the content of each item and save it to check for modifications

**Comment by stephendade** [comment]
> ie if a Fixed date has been added, there should be some version number/last changed date so the alert can be displayed to the user.

Would this be on a per-alert basis or a last-date-changed for the entire manifest?

**Comment by meee1** [comment]
yeah, i just wanted a way to detect changes so i can display/not display it is the user has already acknowledged it. i last modified date item would archive this. im just trying to make it easier

**Comment by stephendade** [comment]
It's a good idea - definitely keep coming with any ideas that make GCS integration easier.

I'll (hopefully) be able to sort this and your other issue in the next few days.
